<?php
/**
 * Plugin Name:       Redirect Emails on Staging
 * Plugin URI:        http://wordpress.org/plugins/redirect-emails-on-staging/
 * Description:       (For WP Engine only) On the Staging site, redirect all emails to the site admin. This is useful in making sure that the staging site doesn't send out confusing emails to your users.
 * Version:           1.1
 * Author:            Jeremy Pry
 * Author URI:        https://jeremypry.com/
 * License:           GPL2
 * Requires at least: 3.5.2
 * Requires PHP:      5.3.2
 * Text Domain:       redirect-emails-on-staging
 */

use Automattic\Jetpack\Identity_Crisis as IdentityCrisis;

// Prevent direct access to this file
if ( ! defined( 'ABSPATH' ) ) {
	die( "You can't do anything by accessing this file directly." );
}

define( 'JPRY_REDIRECT_EMAILS_ON_STAGING_VERSION', '1.1' ); // WRCS: DEFINED_VERSION.

add_filter(
	'wp_mail',
	function( $mail_args ) {
		// Check on WP Engine hosting (the original purpose of this plugin).
		$wpe_staging = function_exists( 'is_wpe_snapshot' ) && is_wpe_snapshot();

		// Check with Jetpack.
		$jetpack_staging = class_exists( IdentityCrisis::class ) && ( IdentityCrisis::has_identity_crisis() || IdentityCrisis::safe_mode_is_confirmed() );

		// Bail if we're not in a staging situation.
		if ( ! ( $wpe_staging || $jetpack_staging ) ) {
			return $mail_args;
		}

		/**
		 * Filter jpry_redirect_staging_emails_email.
		 *
		 * @since x.x.x
		 *
		 * @var string $email The email address where all emails generated by the site should be sent.
		 */
		$email = apply_filters( 'jpry_redirect_staging_emails_email', get_site_option( 'admin_email' ) );

		// If the email is already to the admin, then no need to modify anything.
		if ( $email === $mail_args['to'] ) {
			return $mail_args;
		}

		// We've established that we need to modify the email arguments, so let's do so.
		$mail_args['message'] = sprintf(
			/* translators: 1: original email address, 2: the original message */
			esc_html__( "Originally sent to: %1\$s\n\n%2\$s", 'redirect-emails-on-staging' ),
			$mail_args['to'],
			$mail_args['message']
		);

		$mail_args['subject'] = sprintf(
			/* translators: %s is the original email subject */
			esc_html__( 'REDIRECTED EMAIL | %s', 'redirect-emails-on-staging' ),
			$mail_args['subject']
		);

		$mail_args['to'] = $email;

		return $mail_args;
	},
	99999
);
